fixed analysis issues and added support for dart 3
ShadyBoukhary/flutter_clean_architecture pull request #93
Opened 2023-07-18 09:08 UTC by masnun-siam

## Description

Fixed the analysis issues and added support for Dart 3

*...*

2023-08-25 18:33 UTC, ShadyBoukhary requested changes
Can you respond to the comments?
The tests are failing due to compilation errors after remove Future<>. You'll need to update the test package.

Also, why did you remove Future<>? I also see you made a lot of variables nullable. Can you explain why?

2023-08-25 18:33 UTC, ShadyBoukhary commented on lib/src/background_usecase.dart
> +  Stream<T?> buildUseCaseStream(params) =>
Why?

2023-08-25 18:33 UTC, ShadyBoukhary commented on example/lib/src/app/pages/home/home_presenter.dart
> +  Function? getUserOnNext;
Why?

2023-08-25 18:33 UTC, ShadyBoukhary commented on example/lib/src/domain/usecases/get_user_usecase.dart
> +    yield* controller.stream;
Can you explain the remove of Futures and replacement with this syntax?

2023-08-28 12:04 UTC, closed without merging

2023-08-28 22:01 UTC, ShadyBoukhary commented
@masnun-siam did you mean to close this? I was going to check it in after the tests pass

2023-08-28 23:31 UTC, masnun-siam commented
Sorry about not replying to the comments. Actually, it's been a while since I made the PR and when I saw your comments, I reviewed the changes I made but some of the lines didn't make sense to me either. I actually forgot why I made those changes at the first place. Also, it was one of my first PRs so I didn't check any of the tests before I made the PR so I wanted to close it and recreate it properly on my weekends if the issue still exists.

2023-08-28 23:40 UTC, ShadyBoukhary commented
Okay, feel free to create a new one